In [85]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('../data/email_best_send_time_train.csv')

In [3]:
df.head()

MailID  \
0  2381407D-FF81-4D6B-BFAC-D967720C4F7E   
1  519CA2A6-F77D-4A75-9D2B-536EFCE4E9A1   
2  435FA79E-0EBB-4484-95EC-45632EE04057   
3  8BB6F9A2-9E19-41E2-9AD5-ED27A22C56B8   
4  6A389548-9C49-4C7B-AF09-CCFC56026611   

                                             Subject  \
0  "AJ, thank you for your interest in Revenue In...   
1                                         "Hi Greg!"   
2                                "RE: We're of use!"   
3                                   "RE: Hi Thomas!"   
4                                     "RE: Hi Hill!"   

                              MailBoxID                             ContactID  \
0  66BCC422-78B0-4AE2-9D97-CACD6E60CC00  448CB3F3-B762-4C49-8690-41EE0ED874B3   
1  BC150574-818E-4E7E-A8BA-5FF89FA58BD3  D6574190-E0B2-4AD2-BCF7-CB436E957907   
2  0111BDE3-CC64-4276-98C2-FB1B8B506C05  EF3E3347-ECF5-4653-A5B1-AA599BDD0419   
3  66BCC422-78B0-4AE2-9D97-CACD6E60CC00  DBF9EFE2-1062-4213-9C44-74A941E06096   
4  66C24EAB-51C7-4B5F-EFCA-08D6D3CCF2FF  44799F61-76DF-4F6F-A37D-04DB88473C8C   

                                   TimeZone   SentOn  Opened  
0  "(UTC-08:00) Pacific Time (US & Canada)"  39:23.6       0  
1  "(UTC-06:00) Central Time (US & Canada)"  47:19.0       1  
2  "(UTC-05:00) Eastern Time (US & Canada)"  07:46.2       1  
3  "(UTC-08:00) Pacific Time (US & Canada)"  31:32.7       0  
4  "(UTC-08:00) Pacific Time (US & Canada)"  01:45.1       0

In [53]:
df.shape

(100458, 7)

In [89]:
def get_split_time(time_series: pd.Series):
    parsed_time = []
    for row in list(time_series):
        if isinstance(row, str):
            parsed_time.append([int(val) for val in row.replace('.', ':').split(':')])
        else:
            parsed_time.append([0, 0, 0])
    parsed_time = np.array(parsed_time)
    return parsed_time[:, 0], parsed_time[:, 1], parsed_time[:, 2]

In [90]:
m, s, ms = get_split_time(df.SentOn)

In [91]:
print(m)
print(s)
print(ms)

[39 47  7 ... 17 48 37]
[23 19 46 ... 33 57 34]
[6 0 2 ... 7 6 2]


# text features
from subject - ner (name), contains "re", contains "!"

In [93]:
import spacy

In [98]:
nlp = spacy.load('en_core_web_sm')

In [120]:
doc = nlp(df.Subject[2])

In [121]:
[ent.label_ for ent in doc.ents]

[]

In [122]:
doc.ents

()